version: "3.7"
services:
  caddy:
    image: caddy
    container_name: caddy
    ports: 
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
      
  v2ray:
    image: v2fly/v2fly-core
    container_name: v2ray
    expose:
      - 10000
    command: run -c /etc/v2ray/config.json
    volumes:
      - ./v2ray-server.json:/etc/v2ray/config.json
    restart: unless-stopped

  speedtest:
    image: ghcr.io/librespeed/speedtest:latest
    container_name: speedtest
    expose:
      - 80
    environment:
      - MODE=standalone
      - TITLE=网络测速
      - TELEMETRY=false
      - WEBPORT=80
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
